create table ayuntamiento (ayuntamientoId varchar(255) not null, comunidadAutonomaId varchar(255) not null, geometry CLOB not null, name varchar(255) not null, phone varchar(255), provinciaId varchar(255) not null, primary key (ayuntamientoId));;

create table barrio (barrio_id bigint generated by default as identity, ayuntamientoId varchar(255) not null, geometry CLOB not null, name varchar(255) not null, primary key (barrio_id));;

create table codigo_postal (codigo_ine varchar(255) not null, codigo_postal varchar(5) not null, geometry CLOB not null, primary key (codigo_ine));;

create table CODIGO_POSTAL_AYUNTAMIENTO (codigo_ine varchar(255) not null, ayuntamientoId varchar(255) not null, primary key (codigo_ine, ayuntamientoId));;

create table comunidad_autonoma (comunidadAutonomaId varchar(255) not null, geometry CLOB, name varchar(255) not null, primary key (comunidadAutonomaId));;

create table google_amenity (place_id varchar(255) not null, chain varchar(100) not null, created_at timestamp(6) with time zone not null, latitude float(53) not null, longitude float(53) not null, name varchar(500) not null, previous_place_id varchar(255), primary key (place_id));;

create table google_amenity_snapshot (id bigint generated by default as identity, first_seen timestamp(6) with time zone not null, last_seen timestamp(6) with time zone not null, opening_hours jsonb not null, place_id varchar(255) not null, rating float(53), status varchar(50) not null, user_rating_count integer, primary key (id));;

create table idealist_terrain_price_records (id bigint generated by default as identity, price bigint not null, property_code bigint not null, recorded_at bigint not null, primary key (id));;

create table idealista_ayuntamiento_location (idealista_ayuntamiento_location_id varchar(255) not null, provinciaId varchar(255), primary key (idealista_ayuntamiento_location_id));;

create table idealista_contact_information (id bigint generated by default as identity, contact_name varchar(255), phone_number bigint, prefix bigint, user_type varchar(255), primary key (id));;

create table idealista_location_mapping (id bigint generated by default as identity, acantilado_ayuntamiento_id varchar(255) not null, acantilado_municipality_name varchar(255) not null, idealista_location_id varchar(255) not null, idealista_municipality_name varchar(255) not null, primary key (id));;

create table idealista_property (property_code bigint not null, acantilado_location_id varchar(255) not null, address varchar(255), bathrooms integer, description TEXT, energy_certificate varchar(255), first_seen bigint not null, floor varchar(255), has_air_conditioning boolean, has_box_room boolean, has_garden boolean, has_lift boolean, has_parking_space boolean, has_pool boolean, has_terrace boolean, last_seen bigint not null, latitude float(53) not null, location_id varchar(255), longitude float(53) not null, municipality varchar(255) not null, new_development boolean, new_property boolean, operation varchar(255) not null, parking_included_in_price boolean, property_type varchar(255), rooms integer, size bigint, status varchar(255), sub_typology varchar(255), contact_phone_number bigint, primary key (property_code));;

create table idealista_property_price_records (id bigint generated by default as identity, price bigint not null, property_code bigint not null, recorded_at bigint not null, primary key (id));;

create table idealista_terrain (property_code bigint not null, acantilado_location_id varchar(255) not null, address varchar(255), description TEXT, first_seen bigint not null, last_seen bigint not null, latitude float(53) not null, location_id varchar(255), longitude float(53) not null, municipality varchar(255) not null, operation varchar(255) not null, size bigint, sub_typology varchar(255), contact_phone_number bigint, primary key (property_code));;

create table provincia (provinciaId varchar(255) not null, comunidadAutonomaId varchar(255) not null, geometry CLOB, name varchar(255) not null, primary key (provinciaId));;

alter table if exists CODIGO_POSTAL_AYUNTAMIENTO add constraint FKjc2hbo45yyiy6r1vg8h2nhg9h foreign key (ayuntamientoId) references ayuntamiento;;

alter table if exists CODIGO_POSTAL_AYUNTAMIENTO add constraint FKgby69w96lrisnogf1hxmqang4 foreign key (codigo_ine) references codigo_postal;;

alter table if exists idealist_terrain_price_records add constraint FK5v5jd6aa2y20sytfrvmfiiago foreign key (property_code) references idealista_terrain;;

alter table if exists idealista_property add constraint FKrm59qov0emp46gs87gw5gn4ln foreign key (contact_phone_number) references idealista_contact_information;;

alter table if exists idealista_property_price_records add constraint FK86ae398fdkpprvb389g0s7nc0 foreign key (property_code) references idealista_property;;

alter table if exists idealista_terrain add constraint FKpqjiv5thmlunssxmvan8ptu05 foreign key (contact_phone_number) references idealista_contact_information;;

