
    create table AIRCRAFT (
       aircraft_id bigint not null,
        model varchar(255),
        primary key (aircraft_id)
    );

    create table AIRPORT (
       airport_id bigint not null,
        city varchar(255) not null,
        country varchar(255) not null,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table CARRIER (
       carrier_id bigint not null,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table FLIGHT (
       flight_id bigint generated by default as identity,
        actual_arrival timestamp,
        actual_departure timestamp,
        scheduled_arrival timestamp,
        scheduled_departure timestamp,
        airport_actual_arrival bigint,
        aircraft_id bigint,
        carrier bigint,
        airport_departure bigint,
        operator bigint,
        airport_scheduled_arrival bigint,
        primary key (flight_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table FLIGHT 
       add constraint FK9cii5ir288jxdk3mfkvgph7p3 
       foreign key (airport_actual_arrival) 
       references AIRPORT;

    alter table FLIGHT 
       add constraint FKe5wmmgbp4yrp4r9n3jhjr6lhl 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table FLIGHT 
       add constraint FKt9latawsy1ipguh2e1p8rox2v 
       foreign key (carrier) 
       references CARRIER;

    alter table FLIGHT 
       add constraint FKbgjygm8ye9veqln84reabgrew 
       foreign key (airport_departure) 
       references AIRPORT;

    alter table FLIGHT 
       add constraint FKmu1shuighiugdjpmla7ju8b6w 
       foreign key (operator) 
       references CARRIER;

    alter table FLIGHT 
       add constraint FK5w1iv8vmq8btt487cepdfgu5u 
       foreign key (airport_scheduled_arrival) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint not null,
        model varchar(255),
        primary key (aircraft_id)
    );

    create table AIRPORT (
       airport_id bigint not null,
        city varchar(255) not null,
        country varchar(255) not null,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table CARRIER (
       carrier_id bigint not null,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table FLIGHT (
       flight_id bigint generated by default as identity,
        actual_arrival timestamp,
        actual_departure timestamp,
        scheduled_arrival timestamp,
        scheduled_departure timestamp,
        airport_actual_arrival bigint,
        aircraft_id bigint,
        carrier bigint,
        airport_departure bigint,
        operator bigint,
        airport_scheduled_arrival bigint,
        primary key (flight_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table FLIGHT 
       add constraint FK9cii5ir288jxdk3mfkvgph7p3 
       foreign key (airport_actual_arrival) 
       references AIRPORT;

    alter table FLIGHT 
       add constraint FKe5wmmgbp4yrp4r9n3jhjr6lhl 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table FLIGHT 
       add constraint FKt9latawsy1ipguh2e1p8rox2v 
       foreign key (carrier) 
       references CARRIER;

    alter table FLIGHT 
       add constraint FKbgjygm8ye9veqln84reabgrew 
       foreign key (airport_departure) 
       references AIRPORT;

    alter table FLIGHT 
       add constraint FKmu1shuighiugdjpmla7ju8b6w 
       foreign key (operator) 
       references CARRIER;

    alter table FLIGHT 
       add constraint FK5w1iv8vmq8btt487cepdfgu5u 
       foreign key (airport_scheduled_arrival) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint not null,
        model varchar(255),
        primary key (aircraft_id)
    );

    create table AIRPORT (
       airport_id bigint not null,
        city varchar(255) not null,
        country varchar(255) not null,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table CARRIER (
       carrier_id bigint not null,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table FLIGHT (
       flight_id bigint generated by default as identity,
        actual_arrival timestamp,
        actual_departure timestamp,
        scheduled_arrival timestamp,
        scheduled_departure timestamp,
        airport_actual_arrival bigint,
        aircraft_id bigint,
        carrier bigint,
        airport_departure bigint,
        operator bigint,
        airport_scheduled_arrival bigint,
        primary key (flight_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table FLIGHT 
       add constraint FK9cii5ir288jxdk3mfkvgph7p3 
       foreign key (airport_actual_arrival) 
       references AIRPORT;

    alter table FLIGHT 
       add constraint FKe5wmmgbp4yrp4r9n3jhjr6lhl 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table FLIGHT 
       add constraint FKt9latawsy1ipguh2e1p8rox2v 
       foreign key (carrier) 
       references CARRIER;

    alter table FLIGHT 
       add constraint FKbgjygm8ye9veqln84reabgrew 
       foreign key (airport_departure) 
       references AIRPORT;

    alter table FLIGHT 
       add constraint FKmu1shuighiugdjpmla7ju8b6w 
       foreign key (operator) 
       references CARRIER;

    alter table FLIGHT 
       add constraint FK5w1iv8vmq8btt487cepdfgu5u 
       foreign key (airport_scheduled_arrival) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint not null,
        model varchar(255),
        primary key (aircraft_id)
    );

    create table AIRPORT (
       airport_id bigint not null,
        city varchar(255) not null,
        country varchar(255) not null,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table CARRIER (
       carrier_id bigint not null,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table FLIGHT (
       flight_id bigint generated by default as identity,
        actual_arrival timestamp,
        actual_departure timestamp,
        scheduled_arrival timestamp,
        scheduled_departure timestamp,
        airport_actual_arrival bigint,
        aircraft_id bigint,
        carrier bigint,
        airport_departure bigint,
        operator bigint,
        airport_scheduled_arrival bigint,
        primary key (flight_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table FLIGHT 
       add constraint FK9cii5ir288jxdk3mfkvgph7p3 
       foreign key (airport_actual_arrival) 
       references AIRPORT;

    alter table FLIGHT 
       add constraint FKe5wmmgbp4yrp4r9n3jhjr6lhl 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table FLIGHT 
       add constraint FKt9latawsy1ipguh2e1p8rox2v 
       foreign key (carrier) 
       references CARRIER;

    alter table FLIGHT 
       add constraint FKbgjygm8ye9veqln84reabgrew 
       foreign key (airport_departure) 
       references AIRPORT;

    alter table FLIGHT 
       add constraint FKmu1shuighiugdjpmla7ju8b6w 
       foreign key (operator) 
       references CARRIER;

    alter table FLIGHT 
       add constraint FK5w1iv8vmq8btt487cepdfgu5u 
       foreign key (airport_scheduled_arrival) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint not null,
        model varchar(255),
        primary key (aircraft_id)
    );

    create table AIRPORT (
       runway_id bigint not null,
        city varchar(255) not null,
        country varchar(255) not null,
        name varchar(255) not null,
        primary key (runway_id)
    );

    create table CARRIER (
       carrier_id bigint not null,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table FLIGHT (
       flight_id bigint generated by default as identity,
        actual_arrival timestamp,
        actual_departure timestamp,
        flight_number varchar(255),
        scheduled_arrival timestamp,
        scheduled_departure timestamp,
        runway_actual_arrival bigint,
        aircraft_id bigint,
        carrier bigint,
        runway_departure bigint,
        operator bigint,
        runway_scheduled_arrival bigint,
        primary key (flight_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table FLIGHT 
       add constraint FKk14830iin2ugnbpktkccsn5h3 
       foreign key (runway_actual_arrival) 
       references AIRPORT;

    alter table FLIGHT 
       add constraint FKe5wmmgbp4yrp4r9n3jhjr6lhl 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table FLIGHT 
       add constraint FKt9latawsy1ipguh2e1p8rox2v 
       foreign key (carrier) 
       references CARRIER;

    alter table FLIGHT 
       add constraint FK1gx73loiwrhb15pfxfo0kuuex 
       foreign key (runway_departure) 
       references AIRPORT;

    alter table FLIGHT 
       add constraint FKmu1shuighiugdjpmla7ju8b6w 
       foreign key (operator) 
       references CARRIER;

    alter table FLIGHT 
       add constraint FK68a0sn2blp0pg853k6b2w5ibb 
       foreign key (runway_scheduled_arrival) 
       references AIRPORT;
