
    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;

    create table AIRCRAFT (
       aircraft_id bigint generated by default as identity,
        primary key (aircraft_id)
    );

    create table AIRCRAFT_SCHEDULE (
       aircraft_schedule_id bigint generated by default as identity,
        aircraft_id bigint,
        flight_id bigint,
        primary key (aircraft_schedule_id)
    );

    create table AIRPORT (
       airport_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (airport_id)
    );

    create table AIRPORT_SCHEDULE (
       airport_schedule_id bigint generated by default as identity,
        airport_id bigint,
        flight_id bigint,
        primary key (airport_schedule_id)
    );

    create table CARRIER (
       carrier_id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (carrier_id)
    );

    create table CARRIER_SCHEDULE (
       carrier_schedule_id bigint generated by default as identity,
        carrier_id bigint,
        flight_id bigint,
        primary key (carrier_schedule_id)
    );

    create table flight (
       flight_id bigint generated by default as identity,
        primary key (flight_id)
    );

    create table FLIGHT_SCHEDULE (
       time_schedule_id bigint generated by default as identity,
        actualArrival timestamp not null,
        scheduledArrival timestamp not null,
        actualDepature timestamp not null,
        scheduledDepature timestamp not null,
        flight_id bigint,
        primary key (time_schedule_id)
    );

    create table LOCATION (
       location_id bigint generated by default as identity,
        city varchar(255) not null,
        country varchar(255) not null,
        airport_id bigint,
        primary key (location_id)
    );

    create table people (
       id bigint generated by default as identity,
        fullName varchar(255) not null,
        jobTitle varchar(255) not null,
        primary key (id)
    );

    alter table AIRCRAFT_SCHEDULE 
       add constraint FKjsicojemc3epx0govk2mjvsn5 
       foreign key (aircraft_id) 
       references AIRCRAFT;

    alter table AIRCRAFT_SCHEDULE 
       add constraint FK2gvokrkur6iu14lgfqqu6x04 
       foreign key (flight_id) 
       references flight;

    alter table AIRPORT_SCHEDULE 
       add constraint FK7siw9i3akh6cxxgfkngr7ohjc 
       foreign key (airport_id) 
       references AIRPORT;

    alter table AIRPORT_SCHEDULE 
       add constraint FKnxrdn3ghxp448ucdu32oe2vub 
       foreign key (flight_id) 
       references flight;

    alter table CARRIER_SCHEDULE 
       add constraint FKsfhyhupxfyh593j92kkuskxk7 
       foreign key (carrier_id) 
       references CARRIER;

    alter table CARRIER_SCHEDULE 
       add constraint FKg2cpcejpqud0rmtysfft3wlg1 
       foreign key (flight_id) 
       references flight;

    alter table FLIGHT_SCHEDULE 
       add constraint FKfe6gdacb0xt6st52pxnhlbm79 
       foreign key (flight_id) 
       references flight;

    alter table LOCATION 
       add constraint FK759m9ihftvcwq6j2n2ao37vqd 
       foreign key (airport_id) 
       references AIRPORT;
